apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: treak-ingress
  namespace: treak
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: treak.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: treak-backend-svc
                port:
                  number: 9090
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: treak-frontend-svc
                port:
                  number: 80
